# Generated by Django 3.0.1 on 2020-01-13 20:31

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
