# Generated by Django 3.0.1 on 2020-03-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='newsdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
