# Generated by Django 3.0.1 on 2020-01-15 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_auto_20200107_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='technology',
            new_name='contact',
        ),
    ]
