# Generated by Django 3.0.1 on 2020-01-16 03:23

from django.db import migrations, models
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_auto_20200114_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('BK', 'BROOKLYN'), ('QS', 'QUEENS'), ('MT', 'MANHATTAN'), ('SI', 'STATE ISLAND')], default='BK', max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='contact',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
