# Generated by Django 3.0.1 on 2020-01-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_auto_20200115_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='location',
            field=models.CharField(choices=[('BK', 'BROOKLYN'), ('QS', 'QUEENS'), ('MT', 'MANHATTAN'), ('SI', 'STATE ISLAND')], default='BK', max_length=10),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('qz', 'Looking for Rent'), ('cz', 'For Rent')], default='cz', max_length=10),
        ),
    ]
