# Generated by Django 3.0.1 on 2020-01-22 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_auto_20200121_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
