# Generated by Django 3.0.1 on 2020-02-26 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0009_videocomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoComment',
        ),
    ]
