# Generated by Django 3.0.1 on 2020-01-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/avatar/default.jpg', upload_to='static/avatar'),
        ),
    ]
