# Generated by Django 3.0.1 on 2020-01-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar/default.jpg', upload_to='avatar'),
        ),
    ]
