# Generated by Django 3.0.1 on 2020-01-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_auto_20200107_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar/default.jpeg', upload_to='avatar'),
        ),
    ]
